image: "docker:19.03.4"

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.4-dind

stages:
  - test
  - build
  - push

before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker build --pull -f "DockerFile" --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

run_tests:
  image: "python:3.8"
  stage: test
  before_script:
    - pip install pipenv
    - pipenv sync --dev
  script:
    - pipenv run python -m unittest discover -p "*_test.py" -v

push_latest:
  variables:
    GIT_STRATEGY: none
  only:
    - master
  stage: push
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

push_tag:
  variables:
    GIT_STRATEGY: none
  only:
    - tags
  stage: push
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

push_develop:
  variables:
    GIT_STRATEGY: none
  only:
    - develop
  stage: push
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:develop
    - docker push $CI_REGISTRY_IMAGE:develop
