image: "docker:19.03.3"

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.3-dind

stages:
  - build
  - push

before_script:
  - docker info
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker build --pull -f "DockerFile" --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

push_latest:
  variables:
    GIT_STRATEGY: none
  only:
    - master
  stage: push
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
