image: "docker:19.03.3"

stages:
  - build
  - push

before_script:
  - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY_PASSWORD $CI_REGISTRY

variables:
  pipeline_id: $CI_PIPELINE_IID

build_image:
  stage: build
  script:
    - docker build --pull --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

push_latest:
  variables:
    GIT_STRATEGY: none
  only:
    - master
  stage: push
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
