FROM python:3.7.5-slim-buster

COPY ./Pipfile /app/Pipfile
COPY ./Pipfile.lock /app/Pipfile.lock

WORKDIR /app

RUN pip3 install pipenv
RUN pipenv install gunicorn --skip-lock
RUN pipenv install --ignore-pipfile

COPY . /app

EXPOSE 8000
EXPOSE 5000

ENTRYPOINT [ "pipenv", "run" ]
CMD [ "gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "application" ]
