FROM python:3.7-slim-buster

COPY ./Pipfile /app/Pipfile
COPY ./Pipfile.lock /app/Pipfile.lock

WORKDIR /app

RUN pip3 install pipenv
RUN pipenv install

COPY . /app

EXPOSE 5000

CMD ["python", "application.py" ]

ENTRYPOINT [ "pipenv", "run" ]